# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: Yuti Gao
# email: gaoyt9@gmail.com
# description: copyright@https://yuti-gao.github.io/
# url: https://yuti-gao.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: minima
plugins:
  - jekyll-feed

name: 
description: My goal is to keep this website as simple as possible. In the "posts", I share my research travel experiences, books that have enlightened me, hidden curricula of academia (my observations as a PhD student), and occasionally some research findings.
menu:
 - page: About
   url: /about
 - page: Papers
   url: /papers
   links:
    - title: Working papers
      url: "#working-papers"
    - title: Published papers
      url: "#published-papers"
 - page: Research Projects
   url: /research
   links:
    - title: "Project One"
      url: "#project-one"
    - title: "Project Two"
      url: "#project-two"
    - title: "Project Three"
      url: "#project-three"
    - title: "Project Four"
      url: "#project-four"
 - page: Curriculum Vitae
   url: /cv
   links:
    - title: Experience
      url: "#experience"
    - title: Education
      url: "#education"
    - title: Positions
      url: "#positions"
    - title: Miscellaneous
      url: "#miscellaneous"
 - page: Teaching
   url: /teaching
 - page: Media
   url: /media
 - page: Accolades
   url: /accolades
menu_external:
 - title: OleVik.me
   url: "http://olevik.me/"
 - title: Research Gate
   url: "https://www.researchgate.net/profile/Ole_Vik"
 - title: LinkedIn
   url: "https://no.linkedin.com/in/olehhvik"
 - title: Twitter
   url: "https://twitter.com/olehhv"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: 
locale: en_GB
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
